project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

filters:
- nceas-learning-hub/theme
- quarto-ext/fontawesome
exercises: ### for custom theme callouts
  number: true ### see https://cambiotraining.github.io/quarto-course-template/materials/02-content_guidelines.html
editor: source
execute:
  freeze: auto

format:
  theme-html:
    code-annotations: hover       ### tool tip style footnotes for code
    link-external-newwindow: true ### sets {target = "_blank"} for external links
    link-external-icon: true      ### adds icon to external links

website:
  title: "test"
  reader-mode: false
  repo-url: https://github.com/nceas-learning-hub/test

  ### learning hub logo on browser tab
  favicon: _extensions/nceas-learning-hub/theme/banner/logo_lh_hex.png

  bread-crumbs: false
  navbar:
    right:
      - text: "Instructors"
        menu:
          - text: "Casey O'Hara"
            href: https://www.oharascience.com/
      - icon: github
        href: https://github.com/nceas-learning-hub/test
        aria-label: GitHub

  sidebar:
    title: "Training Materials"
    style: "floating"
    search: true
    tools:
      - icon: house-door-fill
        href: https://www.nceas.ucsb.edu/learning-hub
      - icon: twitter
        href: https://twitter.com/ucsb_nceas
      - icon: github
        href: https://github.com/nceas-learning-hub/test
    contents:
      - index.qmd # preface
      # START SESSIONS
      - s01_git_advanced_git_github.qmd
      - s02_git_setup.qmd
      - s03_github_collaboration.qmd
      - s04_github_introduction.qmd
      - s05_r_git_install_guide.qmd
      - s06_r_practice_clean_wrangle_visualize.qmd
      # END SESSIONS

  page-footer:
    center: "Copyright \u00a9 2026, NCEAS"
    ### NCEAS main website footer:
    # center: "\u00a9 The Regents of the University of California, All Rights Reserved"
    # could also include license info?


